#  Wafer fault Prediction
**Brief:** In electronics, a **wafer** (also called a slice or substrate) is a thin slice of semiconductor, such as a crystalline silicon (c-Si), used for the fabrication of integrated circuits and, in photovoltaics, to manufacture solar cells. The wafer serves as the substrate(serves as foundation for contruction of other components) for microelectronic devices built in and upon the wafer. 

It undergoes many microfabrication processes, such as doping, ion implantation, etching, thin-film deposition of various materials, and photolithographic patterning. Finally, the individual microcircuits are separated by wafer dicing and packaged as an integrated circuit.

## Problem Statement

**Data:** Wafers data


**Problem Statement:** Wafers are predominantly used to manufacture solar cells and are located at remote locations in bulk and they themselves consist of few hundreds of sensors. Wafers are fundamental of photovoltaic power generation, and production thereof requires high technology. Photovoltaic power generation system converts sunlight energy directly to electrical energy.

The motto behind figuring out the faulty wafers is to obliterate the need of having manual man-power doing the same. And make no mistake when we're saying this, even when they suspect a certain wafer to be faulty, they had to open the wafer from the scratch and deal with the issue, and by doing so all the wafers in the vicinity had to be stopped disrupting the whole process and stuff anf this is when that certain wafer was indeed faulty, however, when their suspicion came outta be false negative, then we can only imagine the waste of time, man-power and ofcourse, cost incurred.

**Solution:** Data fetched by wafers is to be passed through the machine learning pipeline and it is to be determined whether the wafer at hand is faulty or not apparently obliterating the need and thus cost of hiring manual labour.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statistics as st
import warnings
warnings.filterwarnings("ignore")
sns.set(rc={"figure.figsize":(15,6)})
pd.pandas.set_option("display.max_columns",None)

In [2]:
d1 = pd.read_csv("Wafer1.csv")
d2 = pd.read_csv("Wafer2.csv")
d3 = pd.read_csv("Wafer3.csv")
d4 = pd.read_csv("Wafer4.csv")
d5 = pd.read_csv("Wafer5.csv")
d6 = pd.read_csv("Wafer6.csv")
d7 = pd.read_csv("Wafer7.csv")
d8 = pd.read_csv("Wafer8.csv")
d9 = pd.read_csv("Wafer9.csv")
d10 = pd.read_csv("Wafer10.csv")
d11 = pd.read_csv("Wafer11.csv")
d12 = pd.read_csv("Wafer12.csv")
d13 = pd.read_csv("Wafer13.csv")
d14 = pd.read_csv("Wafer14.csv")
d15 = pd.read_csv("Wafer15.csv")
d16 = pd.read_csv("Wafer16.csv")

In [3]:
# Concat all the dataframes and create one data frame 
data = pd.concat([d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16],axis=0)

In [4]:
# drop unwanted columns
data.drop(["Unnamed: 554","Unnamed: 555","Unnamed: 556","Unnamed: 557","Unnamed: 558","Unnamed: 559","Unnamed: 560","Unnamed: 561","Unnamed: 562","Unnamed: 563","Unnamed: 564","Unnamed: 565","Unnamed: 566","Unnamed: 567","Unnamed: 568","Unnamed: 569","Unnamed: 570","Unnamed: 571","Unnamed: 572","Unnamed: 573","Unnamed: 574","Unnamed: 575","Unnamed: 576","Unnamed: 577","Unnamed: 578","Unnamed: 579","Unnamed: 580","Unnamed: 581","Unnamed: 582","Unnamed: 583","Unnamed: 584","Unnamed: 585","Unnamed: 586","Unnamed: 587","Unnamed: 588","Unnamed: 589","Unnamed: 590"],axis=1,inplace=True)

In [5]:
data

Unnamed: 0  Sensor-1  Sensor-2   Sensor-3   Sensor-4  Sensor-5  Sensor-6  \
0   Wafer-800   3002.22   2462.06  2202.1222  1833.3772    1.8005     100.0   
1   Wafer-500   3047.28   2186.06  2235.0556  1302.6607    1.6347     100.0   
2   Wafer-501   3076.81   2158.75  2208.2334  1517.0152    1.0980     100.0   
3   Wafer-502   2951.62   2511.92  2253.5111  1397.5060    0.9660     100.0   
4   Wafer-503   2930.42   2505.17  2235.0556  1302.6607    1.6347     100.0   
..        ...       ...       ...        ...        ...       ...       ...   
95  Wafer-396   3079.17   2405.56  2217.3777  1425.1041    1.7585     100.0   
96  Wafer-397   2911.37   2541.21  2207.8111  1202.4520    1.6219     100.0   
97  Wafer-398   3085.57   2364.78  2178.6889  1657.3518    1.6603     100.0   
98  Wafer-399   3053.49   2457.08  2172.5333  1351.9648    1.6377     100.0   
99  Wafer-400   3120.68   2396.40  2177.0222  1448.8499    1.5565     100.0   

    Sensor-7  Sensor-8  Sensor-9  Sensor-10  Sensor-11  Sensor-12  Sensor-13  \
0    95.8500    0.1242    1.5173     0.0069     0.0075     0.9442   203.4157   
1   109.9856    0.1230    1.4619     0.0189    -0.0060     0.9651   197.1621   
2   110.1900    0.1247    1.4357     0.0089     0.0052     0.9655   199.7795   
3   109.7611    0.1210    1.5527     0.0119    -0.0082     0.9572   199.7862   
4   109.9856    0.1230    1.4588    -0.0143     0.0017     0.9702   198.3353   
..       ...       ...       ...        ...        ...        ...        ...   
95  106.2556    0.1200    1.4794    -0.0198    -0.0004     0.9535   197.4874   
96  108.7689    0.1212    1.5322     0.0205    -0.0213     0.9561   198.5870   
97  100.8022    0.1229    1.4945     0.0247    -0.0049     0.9560   198.6292   
98  103.8800    0.1243    1.5680     0.0009     0.0094     0.9560   198.1353   
99  103.2567    0.1232    1.4920    -0.0095     0.0165     0.9525   203.9795   

    Sensor-14  Sensor-15  Sensor-16  Sensor-17  Sensor-18  Sensor-19  \
0         0.0     3.8103   404.6972     9.6640     0.9699   193.7516   
1         0.0     2.2935   817.0030     9.9475     0.9790   187.2146   
2         0.0     9.5309   412.8315    10.3272     0.9715   189.4522   
3         0.0    11.6535   413.2373    10.5044     0.9737   189.2818   
4         0.0    10.4761   420.1418    10.1210     0.9802   188.2143   
..        ...        ...        ...        ...        ...        ...   
95        0.0     8.0655   419.1988    10.2912     0.9719   187.1962   
96        0.0     5.9071   397.4344    10.0264     0.9718   188.5607   
97        0.0     8.2483   427.5357    10.1473     0.9713   188.4820   
98        0.0     6.0246   398.1607    10.0805     0.9716   188.0548   
99        0.0    10.9552   418.5165    10.0922     0.9703   193.8873   

    Sensor-20  Sensor-21  Sensor-22  Sensor-23  Sensor-24  Sensor-25  \
0     12.4349     1.4058   -5578.75    2469.50 -4240.7500  6564.2500   
1     12.5451     1.3933   -5394.75    2763.50 -3974.0000  -312.5000   
2     12.5031     1.3936   -6273.75    3099.50 -6286.7500  1542.0000   
3     12.4673     1.3879   -6368.50    3016.25 -4134.3333  1526.5000   
4     12.5031     1.4147   -5319.25    2691.00 -2732.5000 -1411.5000   
..        ...        ...        ...        ...        ...        ...   
95    12.6006     1.3977   -6047.00    2653.50 -3526.0000 -3200.6667   
96    12.5302     1.3878   -6336.00    3128.50 -3726.0000  1375.2500   
97    12.5302     1.4195   -5932.00    2641.50 -4334.2500    44.0000   
98    12.5894     1.4130   -5427.75    2765.75 -3937.7500 -5292.0000   
99    12.5227     1.3809   -6467.25    2963.00 -2685.7500  1347.7500   

    Sensor-26  Sensor-27  Sensor-28  Sensor-29  Sensor-30  Sensor-31  \
0      1.2837     2.0383     7.3445    70.1667     1.9889     0.1701   
1      1.2680     2.0190     7.3115    69.0667     2.8667     0.2298   
2      0.9815     1.8963     5.1583    69.6111     2.3778     0.1511   
3      0.9712     1.8872     5.0670    68.1111     2.0889     0.1519   
4  

In [6]:
# Check with null values 
data.isnull().sum()

Unnamed: 0      0
Sensor-1        7
Sensor-2        6
Sensor-3       23
Sensor-4       23
             ... 
Sensor-587    100
Sensor-588    100
Sensor-589    100
Sensor-590    100
Good/Bad      639
Length: 592, dtype: int64

In [7]:
# fill all null values with median 
data = data.fillna(data.median())

In [8]:
# drop use less column
data.drop(["Sensor-586","Sensor-332","Sensor-576"],axis=1,inplace=True)

In [9]:
# check the duplicet values
data.duplicated().sum()

283

In [10]:
# drop all dupllicet values from data 
data.drop_duplicates(inplace=True)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1256 entries, 0 to 99
Columns: 589 entries, Unnamed: 0 to Good/Bad
dtypes: float64(588), object(1)
memory usage: 5.7+ MB


In [12]:
data.drop("Unnamed: 0",axis=1,inplace=True)

In [13]:
data

Sensor-1  Sensor-2   Sensor-3   Sensor-4  Sensor-5  Sensor-6  Sensor-7  \
0    3002.22   2462.06  2202.1222  1833.3772    1.8005     100.0   95.8500   
1    3047.28   2186.06  2235.0556  1302.6607    1.6347     100.0  109.9856   
2    3076.81   2158.75  2208.2334  1517.0152    1.0980     100.0  110.1900   
3    2951.62   2511.92  2253.5111  1397.5060    0.9660     100.0  109.7611   
4    2930.42   2505.17  2235.0556  1302.6607    1.6347     100.0  109.9856   
..       ...       ...        ...        ...       ...       ...       ...   
43   3118.63   2478.88  2170.5444   921.0605    1.4390     100.0  104.5300   
62   3013.98   2488.76  2167.5000  1068.4521    1.3719     100.0  102.1733   
76   2917.09   2518.96  2213.7556  1113.5599    0.7217     100.0  104.1667   
94   2977.43   2297.30  2218.0555  1517.4371    0.8579     100.0  105.8133   
99   3120.68   2396.40  2177.0222  1448.8499    1.5565     100.0  103.2567   

    Sensor-8  Sensor-9  Sensor-10  Sensor-11  Sensor-12  Sensor-13  Sensor-14  \
0     0.1242    1.5173     0.0069     0.0075     0.9442   203.4157        0.0   
1     0.1230    1.4619     0.0189    -0.0060     0.9651   197.1621        0.0   
2     0.1247    1.4357     0.0089     0.0052     0.9655   199.7795        0.0   
3     0.1210    1.5527     0.0119    -0.0082     0.9572   199.7862        0.0   
4     0.1230    1.4588    -0.0143     0.0017     0.9702   198.3353        0.0   
..       ...       ...        ...        ...        ...        ...        ...   
43    0.1226    1.4385    -0.0029     0.0099     0.9586   199.2032        0.0   
62    0.1223    1.5523    -0.0110     0.0096     0.9496   199.1580        0.0   
76    0.1211    1.4628     0.0163    -0.0264     0.9502   201.1460        0.0   
94    0.1206    1.4849    -0.0020     0.0082     0.9601   196.4381        0.0   
99    0.1232    1.4920    -0.0095     0.0165     0.9525   203.9795        0.0   

    Sensor-15  Sensor-16  Sensor-17  Sensor-18  Sensor-19  Sensor-20  \
0      3.8103   404.6972     9.6640     0.9699   193.7516    12.4349   
1      2.2935   817.0030     9.9475     0.9790   187.2146    12.5451   
2      9.5309   412.8315    10.3272     0.9715   189.4522    12.5031   
3     11.6535   413.2373    10.5044     0.9737   189.2818    12.4673   
4     10.4761   420.1418    10.1210     0.9802   188.2143    12.5031   
..        ...        ...        ...        ...        ...        ...   
43    10.0795   410.1935    10.0764     0.9695   189.1268    12.4616   
62     7.2777   412.9145    10.5503     0.9680   188.6077    12.4753   
76    10.4777   417.8509    10.3872     0.9703   190.7588    12.6278   
94    11.0801   406.0418    11.0543     0.9683   185.3838    12.4616   
99    10.9552   418.5165    10.0922     0.9703   193.8873    12.5227   

    Sensor-21  Sensor-22  Sensor-23  Sensor-24  Sensor-25  Sensor-26  \
0      1.4058   -5578.75    2469.50 -4240.7500  6564.2500     1.2837   
1      1.3933   -5394.75    2763.50 -3974.0000  -312.5000     1.2680   
2      1.3936   -6273.75    3099.50 -6286.7500  1542.0000     0.9815   
3      1.3879   -6368.50    3016.25 -4134.3333  1526.5000     0.9712   
4      1.4147   -5319.25    2691.00 -2732.5000 -1411.5000     1.2933   
..        ...        ...        ...        ...        ...        ...   
43     1.3759   -5120.00    2651.50 -3857.7500 -4475.7500     1.2720   
62     1.3795   -4929.50    2478.50 -3932.0000 -6910.3333     1.3077   
76     1.4275   -5633.25    2782.25 -5749.3333   328.7500     1.2710   
94     1.4237   -5282.75    2627.50 -3855.5000  6476.0000     1.2640   
99     1.3809   -6467.25    2963.00 -2685.7500  1347.7500     0.9715   

    Sensor-27  Sensor-28  Sensor-29  Sensor-30  Sensor-31  Sensor-32  \
0      2.0383     7.3445    70.1667     1.9889     0.1701     3.3818   
1      2.0190     7.3115    69.0667     2.8667     0.2298     3.4664   
2      1.8963     5.1583    69.6111     2.3778     0.1511     4.6859   
3      1.8872     5.0670    68.1111     2.0889     0.1519     4.6560   
4   

In [14]:
# so our target colum is heavely inbalance ve hav to balance lets see 
data["Good/Bad"].value_counts()

-1.0    1204
 1.0      52
Name: Good/Bad, dtype: int64

In [15]:
def get_cols_with_zero_std_dev(df: pd.DataFrame):
    """
    Returns a list of columns names who are having zero standard deviation.
    """
    cols_to_drop = []
    num_cols = [col for col in df.columns if df[col].dtype != 'O']  # numerical cols only
    for col in num_cols:
        if df[col].std() == 0:
            cols_to_drop.append(col)
    return cols_to_drop

In [16]:
df = get_cols_with_zero_std_dev(df=data)

In [17]:
data

Sensor-1  Sensor-2   Sensor-3   Sensor-4  Sensor-5  Sensor-6  Sensor-7  \
0    3002.22   2462.06  2202.1222  1833.3772    1.8005     100.0   95.8500   
1    3047.28   2186.06  2235.0556  1302.6607    1.6347     100.0  109.9856   
2    3076.81   2158.75  2208.2334  1517.0152    1.0980     100.0  110.1900   
3    2951.62   2511.92  2253.5111  1397.5060    0.9660     100.0  109.7611   
4    2930.42   2505.17  2235.0556  1302.6607    1.6347     100.0  109.9856   
..       ...       ...        ...        ...       ...       ...       ...   
43   3118.63   2478.88  2170.5444   921.0605    1.4390     100.0  104.5300   
62   3013.98   2488.76  2167.5000  1068.4521    1.3719     100.0  102.1733   
76   2917.09   2518.96  2213.7556  1113.5599    0.7217     100.0  104.1667   
94   2977.43   2297.30  2218.0555  1517.4371    0.8579     100.0  105.8133   
99   3120.68   2396.40  2177.0222  1448.8499    1.5565     100.0  103.2567   

    Sensor-8  Sensor-9  Sensor-10  Sensor-11  Sensor-12  Sensor-13  Sensor-14  \
0     0.1242    1.5173     0.0069     0.0075     0.9442   203.4157        0.0   
1     0.1230    1.4619     0.0189    -0.0060     0.9651   197.1621        0.0   
2     0.1247    1.4357     0.0089     0.0052     0.9655   199.7795        0.0   
3     0.1210    1.5527     0.0119    -0.0082     0.9572   199.7862        0.0   
4     0.1230    1.4588    -0.0143     0.0017     0.9702   198.3353        0.0   
..       ...       ...        ...        ...        ...        ...        ...   
43    0.1226    1.4385    -0.0029     0.0099     0.9586   199.2032        0.0   
62    0.1223    1.5523    -0.0110     0.0096     0.9496   199.1580        0.0   
76    0.1211    1.4628     0.0163    -0.0264     0.9502   201.1460        0.0   
94    0.1206    1.4849    -0.0020     0.0082     0.9601   196.4381        0.0   
99    0.1232    1.4920    -0.0095     0.0165     0.9525   203.9795        0.0   

    Sensor-15  Sensor-16  Sensor-17  Sensor-18  Sensor-19  Sensor-20  \
0      3.8103   404.6972     9.6640     0.9699   193.7516    12.4349   
1      2.2935   817.0030     9.9475     0.9790   187.2146    12.5451   
2      9.5309   412.8315    10.3272     0.9715   189.4522    12.5031   
3     11.6535   413.2373    10.5044     0.9737   189.2818    12.4673   
4     10.4761   420.1418    10.1210     0.9802   188.2143    12.5031   
..        ...        ...        ...        ...        ...        ...   
43    10.0795   410.1935    10.0764     0.9695   189.1268    12.4616   
62     7.2777   412.9145    10.5503     0.9680   188.6077    12.4753   
76    10.4777   417.8509    10.3872     0.9703   190.7588    12.6278   
94    11.0801   406.0418    11.0543     0.9683   185.3838    12.4616   
99    10.9552   418.5165    10.0922     0.9703   193.8873    12.5227   

    Sensor-21  Sensor-22  Sensor-23  Sensor-24  Sensor-25  Sensor-26  \
0      1.4058   -5578.75    2469.50 -4240.7500  6564.2500     1.2837   
1      1.3933   -5394.75    2763.50 -3974.0000  -312.5000     1.2680   
2      1.3936   -6273.75    3099.50 -6286.7500  1542.0000     0.9815   
3      1.3879   -6368.50    3016.25 -4134.3333  1526.5000     0.9712   
4      1.4147   -5319.25    2691.00 -2732.5000 -1411.5000     1.2933   
..        ...        ...        ...        ...        ...        ...   
43     1.3759   -5120.00    2651.50 -3857.7500 -4475.7500     1.2720   
62     1.3795   -4929.50    2478.50 -3932.0000 -6910.3333     1.3077   
76     1.4275   -5633.25    2782.25 -5749.3333   328.7500     1.2710   
94     1.4237   -5282.75    2627.50 -3855.5000  6476.0000     1.2640   
99     1.3809   -6467.25    2963.00 -2685.7500  1347.7500     0.9715   

    Sensor-27  Sensor-28  Sensor-29  Sensor-30  Sensor-31  Sensor-32  \
0      2.0383     7.3445    70.1667     1.9889     0.1701     3.3818   
1      2.0190     7.3115    69.0667     2.8667     0.2298     3.4664   
2      1.8963     5.1583    69.6111     2.3778     0.1511     4.6859   
3      1.8872     5.0670    68.1111     2.0889     0.1519     4.6560   
4   

In [18]:
# seaprate dependent and indipendent features
x = data.drop("Good/Bad",axis=1)
y = data["Good/Bad"]

In [19]:
# numerical features
numerical_features = x.select_dtypes(exclude="object").columns
print(numerical_features)

Index(['Sensor-1', 'Sensor-2', 'Sensor-3', 'Sensor-4', 'Sensor-5', 'Sensor-6',
       'Sensor-7', 'Sensor-8', 'Sensor-9', 'Sensor-10',
       ...
       'Sensor-580', 'Sensor-581', 'Sensor-582', 'Sensor-583', 'Sensor-584',
       'Sensor-585', 'Sensor-587', 'Sensor-588', 'Sensor-589', 'Sensor-590'],
      dtype='object', length=587)


In [20]:
from sklearn.preprocessing import RobustScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [21]:
# numeric pipline

num_pipline = Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy="median")),
        ("scaler",RobustScaler())
    ]
)

preprocessor = ColumnTransformer([
    ("num_pipline",num_pipline,numerical_features)
])

In [22]:
X_trans = preprocessor.fit_transform(x)

In [23]:
X_trans

array([[-0.05482172, -0.44845776,  0.03429215, ...,  0.46341463,
         0.34615385, -0.59671597],
       [ 0.44221383, -3.73857845,  1.00236776, ...,  0.43902439,
         0.53846154,  0.12032407],
       [ 0.76794529, -4.06413351,  0.21393056, ...,  1.86585366,
         1.69230769, -0.14330796],
       ...,
       [-0.99385048,  0.22983162,  0.37625535, ..., -0.06097561,
         0.        ,  2.37295772],
       [-0.32826848, -2.41251676,  0.50265069, ..., -0.37804878,
        -0.34615385, -1.09977376],
       [ 1.25185451, -1.2311727 , -0.70352107, ...,  0.12195122,
        -0.07692308,  0.53203592]])

In [24]:
from imblearn.combine import SMOTETomek

X, y = X_trans[:, :-1], y
resampler = SMOTETomek(sampling_strategy="auto")
X_res, y_res = resampler.fit_resample(X, y)

In [25]:
X_res.shape

(2404, 586)

In [26]:
y_res.value_counts()

-1.0    1202
 1.0    1202
Name: Good/Bad, dtype: int64

In [27]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_res,y_res,test_size=0.20,random_state=42)

In [28]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1923, 586)
(481, 586)
(1923,)
(481,)


In [39]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score,ConfusionMatrixDisplay,classification_report,confusion_matrix

In [30]:
# Support Vector machine
svm = SVC()
params = {
    "kernel":["poly", "rbf"],
    "gamma":["scale", "auto"],
    "C":[1.0,0.1,10]   
}

In [31]:
randamcv = RandomizedSearchCV(svm,params,cv=5)

In [32]:
randamcv.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1.0, 0.1, 10],
                                        'gamma': ['scale', 'auto'],
                                        'kernel': ['poly', 'rbf']})

In [34]:
randamcv.best_params_

{'kernel': 'rbf', 'gamma': 'auto', 'C': 10}

In [33]:
randamcv.score(X_train,y_train)

0.9921996879875195

In [36]:
ypred = randamcv.predict(X_test)

In [37]:
accuracy_score(y_test,ypred)

0.9771309771309772

In [38]:
print(classification_report(y_test,ypred))

              precision    recall  f1-score   support

        -1.0       0.98      0.98      0.98       250
         1.0       0.98      0.97      0.98       231

    accuracy                           0.98       481
   macro avg       0.98      0.98      0.98       481
weighted avg       0.98      0.98      0.98       481



In [40]:
confusion_matrix(y_test,ypred)

array([[245,   5],
       [  6, 225]], dtype=int64)

In [50]:
#Randomforest
forest = RandomForestClassifier()
params = {
    "n_estimators":[300],
    "criterion":["gini"],
    "max_depth":[8],
    "min_samples_split":[4],
    "min_samples_leaf":[2,]
}

In [51]:
randamcv = RandomizedSearchCV(forest,params,cv=5)

In [52]:
randamcv.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini'], 'max_depth': [8],
                                        'min_samples_leaf': [2],
                                        'min_samples_split': [4],
                                        'n_estimators': [300]})

In [53]:
randamcv.score(X_train,y_train)

0.9916796671866874

In [54]:
ypred = randamcv.predict(X_test)

In [55]:
accuracy_score(y_test,ypred)

0.9896049896049897

In [56]:
print(classification_report(y_test,ypred))

              precision    recall  f1-score   support

        -1.0       0.99      0.99      0.99       250
         1.0       0.99      0.99      0.99       231

    accuracy                           0.99       481
   macro avg       0.99      0.99      0.99       481
weighted avg       0.99      0.99      0.99       481



In [57]:
confusion_matrix(y_test,ypred)

array([[248,   2],
       [  3, 228]], dtype=int64)

In [61]:
# AdaBoosting
adaboost = AdaBoostClassifier(n_estimators= 200,learning_rate=0.1,)

In [62]:
adaboost.fit(X_train,y_train)

AdaBoostClassifier(learning_rate=0.1, n_estimators=200)

In [63]:
adaboost.score(X_train,y_train)

0.9771190847633905

In [64]:
ypred = adaboost.predict(X_test)

In [65]:
accuracy_score(y_test,ypred)

0.9604989604989606

In [66]:
print(classification_report(y_test,ypred))

              precision    recall  f1-score   support

        -1.0       0.98      0.94      0.96       250
         1.0       0.94      0.98      0.96       231

    accuracy                           0.96       481
   macro avg       0.96      0.96      0.96       481
weighted avg       0.96      0.96      0.96       481



In [67]:
confusion_matrix(y_test,ypred)

array([[235,  15],
       [  4, 227]], dtype=int64)

In [68]:
## Gridentboosting
boosting = GradientBoostingClassifier(n_estimators=250,learning_rate=0.1,max_depth=8)

In [69]:
boosting.fit(X_train,y_train)

GradientBoostingClassifier(max_depth=8, n_estimators=250)

In [70]:
boosting.score(X_train,y_train)

0.9937597503900156

In [71]:
ypred = adaboost.predict(X_test)

In [72]:
accuracy_score(y_test,ypred)

0.9604989604989606

In [73]:
print(classification_report(y_test,ypred))

              precision    recall  f1-score   support

        -1.0       0.98      0.94      0.96       250
         1.0       0.94      0.98      0.96       231

    accuracy                           0.96       481
   macro avg       0.96      0.96      0.96       481
weighted avg       0.96      0.96      0.96       481



In [74]:
confusion_matrix(y_test,ypred)

array([[235,  15],
       [  4, 227]], dtype=int64)